### ISSUE TITLE
Add Sign-in with Stacks to next.js template

### ISSUE THREAD

**Issue by friedger** [hirosystems/stacks.js-starters#6]
At least add a comment to study https://github.com/pradel/stacks-next-auth-example to get sign-in with stacks onto  the server.

**Comment by janniks** [comment]
Great project! 👍

**Comment by maryjames77686** [comment]
Hello

**Comment by maryjames77686** [comment]
@janniks how are you doing

**Comment by janniks** [comment]
Hi, how can we help? Feel free to open a new issue with a question ☺️
